root = "." 
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/infiniti ./cmd/main.go"
bin = "./bin/infiniti"
full_bin = "APP_ENV=dev APP_USER=air ./bin/infiniti"
include_ext = ["go", "env"]
exclude_dir = ["bin", "tmp", "vol"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true