version: "3.9"
services:
  infiniti-db:
    image: postgres:14.2
    volumes:
      - ./vol/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
  infiniti-web:
    build: .
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    volumes:
      - .:/infiniti
    depends_on:
      - infiniti-db
    restart: always